version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    command: >
      bash -c
      "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn thu_lost_and_found_backend.wsgi -w 4 -k gthread -b 0.0.0.0:8000"
    volumes:
      - .:/code
      - static-volume:/code/static
      - media-volume:/code/media
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    container_name: ${DB_HOST}
    image: mysql:latest
    env_file: .env
#    volumes:
#      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static-volume:/code/static
      - media-volume:/code/media
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  media-volume:
  static-volume:
